FROM almalinux:8.7

RUN yum update -y
RUN yum install -y python3 python3-pip openssh-server
COPY docker_key.pub /root/.ssh/
RUN cat /root/.ssh/docker_key.pub >> /root/.ssh/authorized_keys
CMD bash -c "ssh-keygen -A && /usr/sbin/sshd -D"