FROM debian:11

RUN apt update -y
RUN apt install -y python3 python3-pip openssh-server
COPY docker_key.pub /root/.ssh/
RUN cat /root/.ssh/docker_key.pub >> /root/.ssh/authorized_keys
CMD bash -c "/etc/init.d/ssh start && sleep infinity"